name: M2 Mess Detector

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  magento-mess-detector:
    name: M2 Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpmd

      - name: Run PHPMD
        run: phpmd . text cleancode,codesize,controversial,design,naming,unusedcode